{{- $pathfile := printf "envs/%s/.config.third-eye" .Values.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-third-eye-config"
  annotations:
    avp.kubernetes.io/path: "configs/data/{{ .Values.name }}-third-eye-config"
data:
  APP_NAME: <APP_NAME>
  AMQP_ENABLE: <AMQP_ENABLE>
  INTERVAL: <INTERVAL>
  ROLLBACK: <ROLLBACK>
  PORT: <PORT>
  TENDERLY_TRACE: <TENDERLY_TRACE>
  DEBT_DC_MATCHING: <DEBT_DC_MATCHING>
  DISABLE_DEBT_ENGINE: <DISABLE_DEBT_ENGINE>
  THROTTLE_DEBT_CAL: <THROTTLE_DEBT_CAL>
  THROTTLE_HRS: <THROTTLE_HRS>
  BATCH_SIZE_FOR_HISTORY: <BATCH_SIZE_FOR_HISTORY>